version: '3'
services:
  web:
    build: .
    image: "${IMAGE_NAME}"
    ports:
      - "5000"
    container_name: "${CONTAINER_NAME}"

  nginx:
    build: ./nginx
    image: "${IMAGE_NAME}_nginx"
    ports:
      - "${PORT}:88"
    container_name: "${CONTAINER_NAME}_nginx"
