version: '3'
services:
  web:
    build: .
    image: "${IMAGE_NAME}"
    ports:
      - "5000"
    container_name: "${CONTAINER_NAME}"

  nginx:
    image: nginx:latest
    ports:
      - "${PORT}:80"
    container_name: "${CONTAINER_NAME}_nginx"
